import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';
import Database from 'better-sqlite3';
import type { TriageDecision } from '../src/control-plane/contracts.ts';
import { IntakeBriefSnapshotStore } from '../src/control-plane/intake-brief-snapshot-store.ts';
import { IntakeConversationStore } from '../src/control-plane/intake-conversation-store.ts';
import { IntakeSnapshotRunAdmissionConflictError, IntakeSnapshotRunAdmissionService, IntakeSnapshotRunAdmissionStore } from '../src/control-plane/intake-snapshot-run-admission-store.ts';
import { IntakeSnapshotTriageStore } from '../src/control-plane/intake-snapshot-triage-store.ts';
import { JobLedger } from '../src/control-plane/ledger.ts';
import { repositories } from '../src/control-plane/repositories.ts';

const principal={id:'operator:intake-admission'},other={id:'operator:other'},now=()=>new Date('2026-09-03T23:30:00.000Z');
const repository=(id:string)=>repositories.find((candidate)=>candidate.id===id);
const seed={source:'github_issue' as const,key:'github:frostyard/frostyard-org#42',title:'Original issue title',body:'Original issue body.',labels:['bobsled:ready'],author:'operator',url:'https://github.com/frostyard/frostyard-org/issues/42'};
const brief={version:1 as const,repositoryId:'frostyard/frostyard-org',objective:'Add a concise immutable capability statement.',context:['The audience is prospective users.'],acceptanceCriteria:['The capability is described in one plain-language sentence.'],constraints:['Preserve the current layout.'],nonGoals:['No redesign.'],assumptions:['Existing styling remains valid.'],unresolvedQuestions:[]};
const ready={route:'ready_for_agent' as const,risk:'low' as const,confidence:0.94,summary:'The final brief is bounded and ready.',rationale:'The outcome is measurable and no product decision remains.',acceptanceCriteria:brief.acceptanceCriteria,missingInformation:[],suggestedLabels:['bobsled:ready' as const],eligibleForOneClick:true};

function fixture(path:string,resolver=repository,decision:TriageDecision=ready){const conversations=new IntakeConversationStore(path,now,resolver),snapshots=new IntakeBriefSnapshotStore(path,now,conversations),triages=new IntakeSnapshotTriageStore(path,now,snapshots,resolver),ledger=new JobLedger(path,now,resolver),admissions=new IntakeSnapshotRunAdmissionStore(path,now,triages,conversations,ledger);const conversation=conversations.create({repositoryId:brief.repositoryId,seed,brief},principal,'conversation'),snapshot=snapshots.finalize({conversationId:conversation.id,expectedVersion:1,reason:'Operator finalized the exact brief for independent triage.'},principal,'snapshot'),triage=triages.reserve({snapshotId:snapshot.id,reason:'Operator requested one independent triage before admission.'},principal,'triage');triages.claim(triage.id,principal);const succeeded=triages.settleSuccess(triage.id,{decision,text:'Independent triage completed.',agentConversationId:'triage-conversation',agentSubmissionId:'triage-submission'},principal);return{conversations,snapshots,triages,ledger,admissions,snapshot,triage:succeeded,close(){admissions.close();triages.close();snapshots.close();conversations.close();ledger.close();}};}

test('admits one run from immutable snapshot and triage evidence',()=>{const root=mkdtempSync(join(tmpdir(),'bobsled-intake-admission-')),path=join(root,'bobsled.db'),value=fixture(path);try{const reserved=value.admissions.reserve({triageId:value.triage.id,reason:'Operator admits this immutable final brief and independent decision.'},principal,'admission');assert.equal(reserved.status,'reserved');assert.equal(reserved.runAdmissionAuthorized,true);const service=new IntakeSnapshotRunAdmissionService(value.admissions,value.ledger),first=service.admit(reserved.id,principal),replay=service.admit(reserved.id,principal);assert.equal(first.admission.status,'succeeded');assert.equal(first.admission.runId,first.run.id);assert.equal(first.admission.executionAuthorized,false);assert.equal(first.admission.githubMutationAuthorized,false);assert.equal(replay.run.id,first.run.id);assert.equal(first.run.status,'pending');assert.equal(first.run.jobs[0]?.workItemSnapshot.source,seed.source);assert.equal(first.run.jobs[0]?.workItemSnapshot.key,seed.key);assert.equal(first.run.jobs[0]?.workItemSnapshot.title,brief.objective);assert.match(first.run.jobs[0]?.workItemSnapshot.body??'',/Acceptance criteria:\n- The capability/);assert.deepEqual(first.run.jobs[0]?.triageDecision,ready);assert.throws(()=>value.admissions.reserve({triageId:value.triage.id,reason:'A competing admission cannot create another run.'},principal,'competing'),IntakeSnapshotRunAdmissionConflictError);assert.throws(()=>value.admissions.get(reserved.id,other),/another principal/);const db=new Database(path);try{assert.equal((db.prepare('SELECT COUNT(*) AS count FROM schema_migrations WHERE version=45').get() as {count:number}).count,1);assert.equal((db.prepare('SELECT COUNT(*) AS count FROM runs WHERE owner_id=?').get(principal.id) as {count:number}).count,1);const jobId=first.run.jobs[0]!.id;db.prepare('UPDATE jobs SET work_item_snapshot_json=? WHERE id=?').run(JSON.stringify({...first.run.jobs[0]!.workItemSnapshot,title:'tampered'}),jobId);}finally{db.close();}assert.throws(()=>value.admissions.get(reserved.id,principal),IntakeSnapshotRunAdmissionConflictError);}finally{value.close();rmSync(root,{recursive:true,force:true});}});

test('recovers a crash between ledger admission and lineage settlement without duplicating the run',()=>{const root=mkdtempSync(join(tmpdir(),'bobsled-intake-admission-recovery-')),path=join(root,'bobsled.db'),value=fixture(path),reason='Prove deterministic recovery across the durable ledgers.';let observerConversations:IntakeConversationStore|undefined,observerSnapshots:IntakeBriefSnapshotStore|undefined,observerTriages:IntakeSnapshotTriageStore|undefined,observerLedger:JobLedger|undefined,observerAdmissions:IntakeSnapshotRunAdmissionStore|undefined;try{const reserved=value.admissions.reserve({triageId:value.triage.id,reason},principal,'admission');observerConversations=new IntakeConversationStore(path,now,repository);observerSnapshots=new IntakeBriefSnapshotStore(path,now,observerConversations);observerTriages=new IntakeSnapshotTriageStore(path,now,observerSnapshots,repository);observerLedger=new JobLedger(path,now,repository);const observer=new IntakeSnapshotRunAdmissionStore(path,now,observerTriages,observerConversations,observerLedger);observerAdmissions=observer;assert.equal(observer.reserve({triageId:value.triage.id,reason},principal,'admission').id,reserved.id);assert.throws(()=>observer.reserve({triageId:value.triage.id,reason:'Changed input cannot reuse this admission key.'},principal,'admission'),IntakeSnapshotRunAdmissionConflictError);const context=value.admissions.contextFor(reserved.id,principal),orphan=value.ledger.admitWithExpectedPolicy({repositoryId:context.repository.id,workItem:context.workItem,triageDecision:context.decision},context.repository,principal,`intake-snapshot:${reserved.id}`),settled=new IntakeSnapshotRunAdmissionService(observer,observerLedger).admit(reserved.id,principal);assert.equal(settled.run.id,orphan.id);assert.equal(settled.admission.runId,orphan.id);assert.equal(value.ledger.list(principal).length,1);assert.equal(value.admissions.get(reserved.id,principal).runId,orphan.id);}finally{observerAdmissions?.close();observerTriages?.close();observerSnapshots?.close();observerConversations?.close();observerLedger?.close();value.close();rmSync(root,{recursive:true,force:true});}});

test('blocks policy drift atomically and remains recoverable before run creation',()=>{const root=mkdtempSync(join(tmpdir(),'bobsled-intake-admission-policy-')),path=join(root,'bobsled.db');let changed=false;const resolver=(id:string)=>{const found=repository(id);return found&&changed?{...found,description:found.description+' changed'}:found;},value=fixture(path,resolver);try{const reserved=value.admissions.reserve({triageId:value.triage.id,reason:'Bind the admitted run to the independently reviewed repository policy.'},principal,'admission'),service=new IntakeSnapshotRunAdmissionService(value.admissions,value.ledger);changed=true;assert.throws(()=>service.admit(reserved.id,principal),/policy changed/);assert.equal(value.ledger.list(principal).length,0);assert.equal(value.admissions.get(reserved.id,principal).status,'reserved');changed=false;assert.equal(service.admit(reserved.id,principal).admission.status,'succeeded');assert.equal(value.ledger.list(principal).length,1);}finally{value.close();rmSync(root,{recursive:true,force:true});}});

test('routes a ready but non-one-click decision through human approval',()=>{const root=mkdtempSync(join(tmpdir(),'bobsled-intake-admission-human-')),path=join(root,'bobsled.db'),decision={...ready,risk:'moderate' as const,eligibleForOneClick:false},value=fixture(path,repository,decision);try{const reserved=value.admissions.reserve({triageId:value.triage.id,reason:'Retain a deliberate human checkpoint for this decision.'},principal,'admission'),result=new IntakeSnapshotRunAdmissionService(value.admissions,value.ledger).admit(reserved.id,principal);assert.equal(result.run.status,'blocked');assert.equal(result.run.jobs[0]?.status,'blocked');}finally{value.close();rmSync(root,{recursive:true,force:true});}});
