import * as v from 'valibot';
import { RepositoryIdSchema, WorkItemSchema } from './contracts.ts';

export const IntakeBriefSchema=v.object({version:v.literal(1),repositoryId:RepositoryIdSchema,objective:v.pipe(v.string(),v.minLength(1),v.maxLength(2_000)),context:v.pipe(v.array(v.pipe(v.string(),v.minLength(1),v.maxLength(2_000))),v.maxLength(30)),acceptanceCriteria:v.pipe(v.array(v.pipe(v.string(),v.minLength(1),v.maxLength(1_000))),v.maxLength(30)),constraints:v.pipe(v.array(v.pipe(v.string(),v.minLength(1),v.maxLength(1_000))),v.maxLength(30)),nonGoals:v.pipe(v.array(v.pipe(v.string(),v.minLength(1),v.maxLength(1_000))),v.maxLength(30)),assumptions:v.pipe(v.array(v.pipe(v.string(),v.minLength(1),v.maxLength(1_000))),v.maxLength(30)),unresolvedQuestions:v.pipe(v.array(v.pipe(v.string(),v.minLength(1),v.maxLength(1_000))),v.maxLength(30))});
export const IntakeConversationTurnSchema=v.object({id:v.pipe(v.string(),v.uuid()),conversationId:v.pipe(v.string(),v.uuid()),sequence:v.pipe(v.number(),v.integer(),v.minValue(1),v.maxValue(100)),role:v.picklist(['operator','assistant']),text:v.pipe(v.string(),v.minLength(1),v.maxLength(20_000)),brief:IntakeBriefSchema,createdAt:v.string()});
export const IntakeConversationSchema=v.object({id:v.pipe(v.string(),v.uuid()),ownerId:v.pipe(v.string(),v.minLength(1),v.maxLength(500)),repositoryId:RepositoryIdSchema,status:v.picklist(['active','cancelled']),version:v.pipe(v.number(),v.integer(),v.minValue(1)),seed:WorkItemSchema,currentBrief:IntakeBriefSchema,turns:v.pipe(v.array(IntakeConversationTurnSchema),v.maxLength(100)),terminalReason:v.optional(v.pipe(v.string(),v.minLength(10),v.maxLength(2_000))),intakeModelCallAuthorized:v.literal(false),runAdmissionAuthorized:v.literal(false),githubMutationAuthorized:v.literal(false),createdAt:v.string(),updatedAt:v.string()});
export const IntakeBriefRevisionOutputSchema=v.object({brief:IntakeBriefSchema,response:v.pipe(v.string(),v.minLength(1),v.maxLength(20_000))});
export const IntakeBriefRevisionInitialDataSchema=v.object({conversationId:v.pipe(v.string(),v.uuid()),repositoryId:RepositoryIdSchema,seed:WorkItemSchema,currentBrief:IntakeBriefSchema,turns:v.pipe(v.array(v.object({role:v.picklist(['operator','assistant']),text:v.pipe(v.string(),v.minLength(1),v.maxLength(20_000)),brief:IntakeBriefSchema})),v.maxLength(100))});

export type IntakeBrief=v.InferOutput<typeof IntakeBriefSchema>;
export type IntakeConversation=v.InferOutput<typeof IntakeConversationSchema>;
export type IntakeBriefRevisionOutput=v.InferOutput<typeof IntakeBriefRevisionOutputSchema>;
export type IntakeBriefRevisionInitialData=v.InferOutput<typeof IntakeBriefRevisionInitialDataSchema>;
