import { randomUUID } from 'node:crypto';
import { chmodSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import Database from 'better-sqlite3';
import * as v from 'valibot';
import { dataPath } from '../paths.ts';
import { IntakeBriefRevisionOutputSchema, IntakeBriefSchema, type IntakeConversation } from './intake-conversation-contracts.ts';
import { IntakeConversationStore, intakeDigest } from './intake-conversation-store.ts';
import { ensureIntakeConversationSchema } from './intake-conversation-schema.ts';
import type { Principal } from './ledger.ts';

const ReserveSchema=v.object({conversationId:v.pipe(v.string(),v.uuid()),expectedVersion:v.pipe(v.number(),v.integer(),v.minValue(1)),message:v.pipe(v.string(),v.minLength(1),v.maxLength(20_000)),reason:v.pipe(v.string(),v.minLength(10),v.maxLength(2_000))});
export const IntakeBriefRevisionCandidateSchema=v.object({...IntakeBriefRevisionOutputSchema.entries,agentConversationId:v.pipe(v.string(),v.minLength(1),v.maxLength(500)),agentSubmissionId:v.pipe(v.string(),v.minLength(1),v.maxLength(500))});
const ResultSchema=v.object({...IntakeBriefRevisionCandidateSchema.entries,conversationVersion:v.pipe(v.number(),v.integer(),v.minValue(3)),modelCalls:v.literal(1),runAdmissionAuthorized:v.literal(false),githubMutationAuthorized:v.literal(false)});
export const IntakeConversationRevisionSchema=v.object({id:v.pipe(v.string(),v.uuid()),conversationId:v.pipe(v.string(),v.uuid()),ownerId:v.string(),baseVersion:v.pipe(v.number(),v.integer(),v.minValue(1)),operatorTurnId:v.pipe(v.string(),v.uuid()),assistantTurnId:v.optional(v.pipe(v.string(),v.uuid())),status:v.picklist(['reserved','running','succeeded','failed']),modelCalls:v.pipe(v.number(),v.integer(),v.minValue(0),v.maxValue(1)),reason:v.pipe(v.string(),v.minLength(10),v.maxLength(2_000)),error:v.optional(v.pipe(v.string(),v.minLength(1),v.maxLength(4_000))),result:v.optional(ResultSchema),modelCallAuthorized:v.boolean(),runAdmissionAuthorized:v.literal(false),githubMutationAuthorized:v.literal(false),createdAt:v.string(),startedAt:v.optional(v.string()),finishedAt:v.optional(v.string())});
export type IntakeBriefRevisionCandidate=v.InferOutput<typeof IntakeBriefRevisionCandidateSchema>;
export type IntakeConversationRevision=v.InferOutput<typeof IntakeConversationRevisionSchema>;
export class IntakeConversationRevisionConflictError extends Error{}
export class IntakeConversationRevisionForbiddenError extends Error{}
export class IntakeConversationRevisionNotFoundError extends Error{}
interface RevisionRow{id:string;conversation_id:string;owner_id:string;idempotency_key:string;request_sha256:string;base_version:number;operator_turn_id:string;assistant_turn_id:string|null;status:string;model_calls:number;reason:string;error:string|null;created_at:string;started_at:string|null;finished_at:string|null;result_sha256:string|null;result_json:string|null}
interface ConversationRow{id:string;owner_id:string;repository_id:string;status:string;version:number;current_brief_sha256:string;current_brief_json:string;updated_at:string}
interface TurnEvidenceRow{id:string;conversation_id:string;owner_id:string;request_sha256:string;sequence:number;role:string;text:string;brief_sha256:string;brief_json:string}

export class IntakeConversationRevisionStore{
	readonly #db:Database.Database;
	readonly #conversations:IntakeConversationStore;
	readonly #ownsConversations:boolean;
	readonly #now:()=>Date;
	constructor(path=dataPath('bobsled.db'),now:()=>Date=()=>new Date(),conversations?:IntakeConversationStore){if(path!==':memory:')mkdirSync(dirname(path),{recursive:true,mode:0o700});this.#db=new Database(path);if(path!==':memory:')chmodSync(path,0o600);this.#db.pragma('foreign_keys = ON');this.#db.pragma('journal_mode = WAL');this.#db.pragma('busy_timeout = 5000');this.#db.exec('CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)');ensureIntakeConversationSchema(this.#db);this.#conversations=conversations??new IntakeConversationStore(path,now);this.#ownsConversations=!conversations;this.#now=now;}
	close():void{if(this.#ownsConversations)this.#conversations.close();this.#db.close();}
	list(conversationId:string,principal:Principal):IntakeConversationRevision[]{this.#conversations.get(conversationId,principal);const rows=this.#db.prepare('SELECT id FROM intake_conversation_revisions WHERE conversation_id=? AND owner_id=? ORDER BY base_version,id').all(conversationId,principal.id) as Array<{id:string}>;return rows.map(({id})=>this.get(id,principal));}
	reserve(input:unknown,principal:Principal,idempotencyKey:string):IntakeConversationRevision{
		const request=v.parse(ReserveSchema,input);if(!idempotencyKey||idempotencyKey.length>200)throw new IntakeConversationRevisionConflictError('A bounded Idempotency-Key is required');const requestSha=intakeDigest(request);const replay=this.#findReplay(principal.id,idempotencyKey);if(replay){if(replay.request_sha256!==requestSha)throw new IntakeConversationRevisionConflictError('Idempotency key was already used for different input');return this.get(replay.id,principal);}
		this.#conversations.get(request.conversationId,principal);
		const revisionId=this.#db.transaction(()=>{const concurrent=this.#findReplay(principal.id,idempotencyKey);if(concurrent){if(concurrent.request_sha256!==requestSha)throw new IntakeConversationRevisionConflictError('Idempotency key was already used for different input');return concurrent.id;}const conversation=this.#ownedConversation(request.conversationId,principal);if(conversation.status!=='active'||conversation.version!==request.expectedVersion)throw new IntakeConversationRevisionConflictError('Conversation is terminal or changed; reload before submitting');const active=this.#db.prepare("SELECT id FROM intake_conversation_revisions WHERE conversation_id=? AND status IN ('reserved','running') LIMIT 1").get(conversation.id);if(active)throw new IntakeConversationRevisionConflictError('Conversation already has an active model revision');const count=(this.#db.prepare('SELECT COUNT(*) AS count FROM intake_conversation_turns WHERE conversation_id=?').get(conversation.id) as {count:number}).count;if(count>98)throw new IntakeConversationRevisionConflictError('Conversation lacks capacity for an operator and assistant turn');const timestamp=this.#now().toISOString(),turnId=randomUUID(),id=randomUUID(),brief=v.parse(IntakeBriefSchema,JSON.parse(conversation.current_brief_json));this.#db.prepare('INSERT INTO intake_conversation_turns (id,conversation_id,owner_id,idempotency_key,request_sha256,sequence,role,text,brief_sha256,brief_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(turnId,conversation.id,principal.id,`${idempotencyKey}:operator`,intakeDigest({message:request.message,brief}),count+1,'operator',request.message,intakeDigest(brief),JSON.stringify(brief),timestamp);const changed=this.#db.prepare("UPDATE intake_conversations SET version=version+1,updated_at=? WHERE id=? AND version=? AND status='active'").run(timestamp,conversation.id,request.expectedVersion);if(changed.changes!==1)throw new IntakeConversationRevisionConflictError('Conversation revision reservation raced with another process');this.#db.prepare(`INSERT INTO intake_conversation_revisions (id,conversation_id,owner_id,idempotency_key,request_sha256,base_version,operator_turn_id,status,reason,created_at) VALUES (?,?,?,?,?,?,?,'reserved',?,?)`).run(id,conversation.id,principal.id,idempotencyKey,requestSha,request.expectedVersion,turnId,request.reason,timestamp);return id;}).immediate();return this.get(revisionId,principal);
	}
	get(id:string,principal:Principal):IntakeConversationRevision{
		const row=this.#db.prepare('SELECT * FROM intake_conversation_revisions WHERE id=?').get(id) as RevisionRow|undefined;if(!row)throw new IntakeConversationRevisionNotFoundError('Conversation revision was not found');if(row.owner_id!==principal.id)throw new IntakeConversationRevisionForbiddenError('Conversation revision belongs to another principal');const conversation=this.#conversations.get(row.conversation_id,principal);const operator=this.#turn(row.operator_turn_id);let operatorBrief:unknown;try{operatorBrief=v.parse(IntakeBriefSchema,JSON.parse(operator.brief_json));}catch{throw new IntakeConversationRevisionConflictError('Stored operator turn is malformed');}if(operator.conversation_id!==row.conversation_id||operator.owner_id!==row.owner_id||operator.role!=='operator'||operator.sequence!==row.base_version||intakeDigest(operatorBrief)!==operator.brief_sha256||operator.request_sha256!==intakeDigest({message:operator.text,brief:operatorBrief})||row.request_sha256!==intakeDigest({conversationId:row.conversation_id,expectedVersion:row.base_version,message:operator.text,reason:row.reason}))throw new IntakeConversationRevisionConflictError('Stored operator turn failed revision parent verification');
		let result:v.InferOutput<typeof ResultSchema>|undefined;let assistant:TurnEvidenceRow|undefined;if(row.result_json){try{result=v.parse(ResultSchema,JSON.parse(row.result_json));}catch{throw new IntakeConversationRevisionConflictError('Stored conversation revision result is malformed');}if(!row.result_sha256||intakeDigest(result)!==row.result_sha256||result.conversationVersion!==row.base_version+2)throw new IntakeConversationRevisionConflictError('Stored conversation revision result failed digest or version verification');if(!row.assistant_turn_id)throw new IntakeConversationRevisionConflictError('Successful revision lacks assistant-turn evidence');assistant=this.#turn(row.assistant_turn_id);let assistantBrief:unknown;try{assistantBrief=v.parse(IntakeBriefSchema,JSON.parse(assistant.brief_json));}catch{throw new IntakeConversationRevisionConflictError('Stored assistant turn is malformed');}if(assistant.conversation_id!==row.conversation_id||assistant.owner_id!==row.owner_id||assistant.role!=='assistant'||assistant.sequence!==row.base_version+1||assistant.text!==result.response||assistant.request_sha256!==intakeDigest(result)||intakeDigest(assistantBrief)!==assistant.brief_sha256||intakeDigest(result.brief)!==assistant.brief_sha256)throw new IntakeConversationRevisionConflictError('Stored assistant turn failed revision result verification');}
		const reserved=row.status==='reserved',running=row.status==='running',succeeded=row.status==='succeeded',failed=row.status==='failed';const validLifecycle=(reserved&&row.model_calls===0&&!row.started_at&&!row.finished_at&&!row.error&&!result&&!assistant&&!row.assistant_turn_id)||(running&&row.model_calls===1&&Boolean(row.started_at)&&!row.finished_at&&!row.error&&!result&&!assistant&&!row.assistant_turn_id)||(succeeded&&row.model_calls===1&&Boolean(row.started_at)&&Boolean(row.finished_at)&&!row.error&&Boolean(result)&&Boolean(assistant)&&Boolean(row.assistant_turn_id))||(failed&&row.model_calls===1&&Boolean(row.started_at)&&Boolean(row.finished_at)&&Boolean(row.error)&&!result&&!assistant&&!row.assistant_turn_id);if(!validLifecycle||conversation.version<row.base_version+1)throw new IntakeConversationRevisionConflictError('Stored conversation revision failed lifecycle verification');
		return v.parse(IntakeConversationRevisionSchema,{id:row.id,conversationId:row.conversation_id,ownerId:row.owner_id,baseVersion:row.base_version,operatorTurnId:row.operator_turn_id,assistantTurnId:row.assistant_turn_id??undefined,status:row.status,modelCalls:row.model_calls,reason:row.reason,error:row.error??undefined,result,modelCallAuthorized:reserved,runAdmissionAuthorized:false,githubMutationAuthorized:false,createdAt:row.created_at,startedAt:row.started_at??undefined,finishedAt:row.finished_at??undefined});
	}
	contextFor(id:string,principal:Principal):IntakeConversation{const revision=this.get(id,principal);const conversation=this.#conversations.get(revision.conversationId,principal);if(conversation.status!=='active'||conversation.version!==revision.baseVersion+1||conversation.turns.at(-1)?.id!==revision.operatorTurnId)throw new IntakeConversationRevisionConflictError('Conversation advanced beyond this pending revision');return conversation;}
	claim(id:string,principal:Principal):{revision:IntakeConversationRevision;newlyClaimed:boolean}{this.contextFor(id,principal);let newlyClaimed=false;this.#db.transaction(()=>{const current=this.get(id,principal);if(current.status!=='reserved')return;const changed=this.#db.prepare("UPDATE intake_conversation_revisions SET status='running',model_calls=1,started_at=? WHERE id=? AND status='reserved' AND model_calls=0").run(this.#now().toISOString(),id);if(changed.changes!==1)throw new IntakeConversationRevisionConflictError('Conversation revision claim raced with another process');newlyClaimed=true;}).immediate();return{revision:this.get(id,principal),newlyClaimed};}
	settleSuccess(id:string,input:unknown,principal:Principal):IntakeConversationRevision{
		const candidate=v.parse(IntakeBriefRevisionCandidateSchema,input);this.#db.transaction(()=>{const current=this.get(id,principal);if(current.status==='succeeded'){const expected={brief:candidate.brief,response:candidate.response,agentConversationId:candidate.agentConversationId,agentSubmissionId:candidate.agentSubmissionId};const actual=current.result&&{brief:current.result.brief,response:current.result.response,agentConversationId:current.result.agentConversationId,agentSubmissionId:current.result.agentSubmissionId};if(intakeDigest(actual)!==intakeDigest(expected))throw new IntakeConversationRevisionConflictError('Terminal revision result is immutable');return;}if(current.status!=='running')throw new IntakeConversationRevisionConflictError('Only a running revision may succeed');const conversation=this.contextFor(id,principal);if(candidate.brief.repositoryId!==conversation.repositoryId)throw new IntakeConversationRevisionConflictError('The intake model cannot change repository selection');const timestamp=this.#now().toISOString(),turnId=randomUUID(),sequence=conversation.turns.length+1,result=v.parse(ResultSchema,{...candidate,conversationVersion:current.baseVersion+2,modelCalls:1,runAdmissionAuthorized:false,githubMutationAuthorized:false});this.#db.prepare('INSERT INTO intake_conversation_turns (id,conversation_id,owner_id,idempotency_key,request_sha256,sequence,role,text,brief_sha256,brief_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(turnId,conversation.id,principal.id,`revision:${id}:assistant`,intakeDigest(result),sequence,'assistant',candidate.response,intakeDigest(candidate.brief),JSON.stringify(candidate.brief),timestamp);const changed=this.#db.prepare("UPDATE intake_conversations SET version=version+1,current_brief_sha256=?,current_brief_json=?,updated_at=? WHERE id=? AND version=? AND status='active'").run(intakeDigest(candidate.brief),JSON.stringify(candidate.brief),timestamp,conversation.id,current.baseVersion+1);if(changed.changes!==1)throw new IntakeConversationRevisionConflictError('Conversation advanced during revision settlement');const settled=this.#db.prepare("UPDATE intake_conversation_revisions SET status='succeeded',assistant_turn_id=?,result_sha256=?,result_json=?,finished_at=? WHERE id=? AND status='running' AND model_calls=1").run(turnId,intakeDigest(result),JSON.stringify(result),timestamp,id);if(settled.changes!==1)throw new IntakeConversationRevisionConflictError('Conversation revision settlement raced with another process');}).immediate();return this.get(id,principal);
	}
	settleFailure(id:string,error:string,principal:Principal):IntakeConversationRevision{if(error.length<1||error.length>4000)throw new IntakeConversationRevisionConflictError('Failure reason must be bounded');this.#db.transaction(()=>{const current=this.get(id,principal);if(current.status==='failed')return;if(current.status!=='running')throw new IntakeConversationRevisionConflictError('Only a claimed revision may fail');const changed=this.#db.prepare("UPDATE intake_conversation_revisions SET status='failed',error=?,finished_at=? WHERE id=? AND status='running' AND model_calls=1").run(error,this.#now().toISOString(),id);if(changed.changes!==1)throw new IntakeConversationRevisionConflictError('Conversation revision failure settlement raced with another process');}).immediate();return this.get(id,principal);}
	#turn(id:string):TurnEvidenceRow{const row=this.#db.prepare('SELECT id,conversation_id,owner_id,request_sha256,sequence,role,text,brief_sha256,brief_json FROM intake_conversation_turns WHERE id=?').get(id) as TurnEvidenceRow|undefined;if(!row)throw new IntakeConversationRevisionConflictError('Stored revision turn is missing');return row;}
	#ownedConversation(id:string,principal:Principal):ConversationRow{const row=this.#db.prepare('SELECT * FROM intake_conversations WHERE id=?').get(id) as ConversationRow|undefined;if(!row)throw new IntakeConversationRevisionNotFoundError('Conversation was not found');if(row.owner_id!==principal.id)throw new IntakeConversationRevisionForbiddenError('Conversation belongs to another principal');return row;}
	#findReplay(owner:string,key:string):RevisionRow|undefined{return this.#db.prepare('SELECT * FROM intake_conversation_revisions WHERE owner_id=? AND idempotency_key=?').get(owner,key) as RevisionRow|undefined;}
}
