import { randomUUID } from 'node:crypto';
import { chmodSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import Database from 'better-sqlite3';
import * as v from 'valibot';
import { dataPath } from '../paths.ts';
import { RepositoryContractSchema, TriageDecisionSchema, WorkItemSchema, type RepositoryContract, type WorkItem } from './contracts.ts';
import { IntakeConversationStore } from './intake-conversation-store.ts';
import { intakeDigest } from './intake-conversation-store.ts';
import { ensureIntakeConversationSchema } from './intake-conversation-schema.ts';
import { IntakeSnapshotTriageStore } from './intake-snapshot-triage-store.ts';
import { JobLedger, type Principal } from './ledger.ts';
import type { RunRecord } from './ledger-contracts.ts';

const Sha256Schema=v.pipe(v.string(),v.regex(/^[a-f0-9]{64}$/));
const ReserveSchema=v.object({triageId:v.pipe(v.string(),v.uuid()),reason:v.pipe(v.string(),v.minLength(10),v.maxLength(2_000))});
export const IntakeSnapshotRunAdmissionSchema=v.object({id:v.pipe(v.string(),v.uuid()),snapshotId:v.pipe(v.string(),v.uuid()),triageId:v.pipe(v.string(),v.uuid()),ownerId:v.pipe(v.string(),v.minLength(1),v.maxLength(500)),repositorySha256:Sha256Schema,workItemSha256:Sha256Schema,triageResultSha256:Sha256Schema,status:v.picklist(['reserved','succeeded']),runId:v.optional(v.pipe(v.string(),v.uuid())),reason:v.pipe(v.string(),v.minLength(10),v.maxLength(2_000)),runAdmissionAuthorized:v.boolean(),executionAuthorized:v.literal(false),githubMutationAuthorized:v.literal(false),createdAt:v.string(),finishedAt:v.optional(v.string())});
export type IntakeSnapshotRunAdmission=v.InferOutput<typeof IntakeSnapshotRunAdmissionSchema>;
export class IntakeSnapshotRunAdmissionConflictError extends Error{}
export class IntakeSnapshotRunAdmissionForbiddenError extends Error{}
export class IntakeSnapshotRunAdmissionNotFoundError extends Error{}

interface AdmissionRow{id:string;snapshot_id:string;triage_id:string;owner_id:string;idempotency_key:string;request_sha256:string;repository_sha256:string;work_item_sha256:string;work_item_json:string;triage_result_sha256:string;status:string;run_id:string|null;reason:string;created_at:string;finished_at:string|null}

function section(title:string,values:string[]):string{return values.length?`${title}:\n${values.map((value)=>`- ${value}`).join('\n')}`:`${title}:\n- None`;}
function deriveWorkItem(seed:WorkItem,brief:{objective:string;context:string[];acceptanceCriteria:string[];constraints:string[];nonGoals:string[];assumptions:string[];unresolvedQuestions:string[]}):WorkItem{return v.parse(WorkItemSchema,{...seed,title:brief.objective,body:[section('Context',brief.context),section('Acceptance criteria',brief.acceptanceCriteria),section('Constraints',brief.constraints),section('Non-goals',brief.nonGoals),section('Assumptions',brief.assumptions),section('Unresolved questions',brief.unresolvedQuestions)].join('\n\n')});}

export class IntakeSnapshotRunAdmissionStore {
	readonly #db:Database.Database;readonly #now:()=>Date;readonly #triages:IntakeSnapshotTriageStore;readonly #conversations:IntakeConversationStore;readonly #ledger:JobLedger;readonly #ownsTriages:boolean;readonly #ownsConversations:boolean;readonly #ownsLedger:boolean;
	constructor(path=dataPath('bobsled.db'),now:()=>Date=()=>new Date(),triages?:IntakeSnapshotTriageStore,conversations?:IntakeConversationStore,ledger?:JobLedger){if(path!==':memory:')mkdirSync(dirname(path),{recursive:true,mode:0o700});this.#db=new Database(path);if(path!==':memory:')chmodSync(path,0o600);this.#db.pragma('foreign_keys = ON');this.#db.pragma('journal_mode = WAL');this.#db.pragma('busy_timeout = 5000');this.#db.exec('CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)');ensureIntakeConversationSchema(this.#db);this.#triages=triages??new IntakeSnapshotTriageStore(path,now);this.#conversations=conversations??new IntakeConversationStore(path,now);this.#ledger=ledger??new JobLedger(path,now);this.#ownsTriages=!triages;this.#ownsConversations=!conversations;this.#ownsLedger=!ledger;this.#now=now;}
	close():void{if(this.#ownsTriages)this.#triages.close();if(this.#ownsConversations)this.#conversations.close();if(this.#ownsLedger)this.#ledger.close();this.#db.close();}
	reserve(input:unknown,principal:Principal,idempotencyKey:string):IntakeSnapshotRunAdmission {const request=v.parse(ReserveSchema,input);if(!idempotencyKey||idempotencyKey.length>200)throw new IntakeSnapshotRunAdmissionConflictError('A bounded Idempotency-Key is required');const requestSha=intakeDigest(request),replay=this.#findReplay(principal.id,idempotencyKey);if(replay){if(replay.request_sha256!==requestSha)throw new IntakeSnapshotRunAdmissionConflictError('Idempotency key was already used for different intake admission input');return this.get(replay.id,principal);}const context=this.#context(request.triageId,principal),workItem=deriveWorkItem(context.conversation.seed,context.snapshot.brief),workItemSha=intakeDigest(workItem),triageResultSha=intakeDigest(context.triage.result),repositorySha=intakeDigest(context.repository);const id=this.#db.transaction(()=>{const concurrent=this.#findReplay(principal.id,idempotencyKey);if(concurrent){if(concurrent.request_sha256!==requestSha)throw new IntakeSnapshotRunAdmissionConflictError('Idempotency key was already used for different intake admission input');return concurrent.id;}if(this.#db.prepare('SELECT id FROM intake_snapshot_run_admissions WHERE triage_id=?').get(request.triageId))throw new IntakeSnapshotRunAdmissionConflictError('Snapshot triage already has a run admission');const admissionId=randomUUID(),timestamp=this.#now().toISOString();this.#db.prepare("INSERT INTO intake_snapshot_run_admissions (id,snapshot_id,triage_id,owner_id,idempotency_key,request_sha256,repository_sha256,work_item_sha256,work_item_json,triage_result_sha256,status,reason,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,'reserved',?,?)").run(admissionId,context.snapshot.id,context.triage.id,principal.id,idempotencyKey,requestSha,repositorySha,workItemSha,JSON.stringify(workItem),triageResultSha,request.reason,timestamp);return admissionId;}).immediate();return this.get(id,principal);}
	get(id:string,principal:Principal):IntakeSnapshotRunAdmission {const row=this.#db.prepare('SELECT * FROM intake_snapshot_run_admissions WHERE id=?').get(id) as AdmissionRow|undefined;if(!row)throw new IntakeSnapshotRunAdmissionNotFoundError('Intake run admission was not found');if(row.owner_id!==principal.id)throw new IntakeSnapshotRunAdmissionForbiddenError('Intake run admission belongs to another principal');const context=this.#context(row.triage_id,principal);let workItem:WorkItem;try{workItem=v.parse(WorkItemSchema,JSON.parse(row.work_item_json));}catch{throw new IntakeSnapshotRunAdmissionConflictError('Stored intake run admission is malformed');}const expected=deriveWorkItem(context.conversation.seed,context.snapshot.brief),succeeded=row.status==='succeeded';if(row.snapshot_id!==context.snapshot.id||row.request_sha256!==intakeDigest({triageId:row.triage_id,reason:row.reason})||row.repository_sha256!==intakeDigest(context.repository)||row.work_item_sha256!==intakeDigest(workItem)||row.work_item_sha256!==intakeDigest(expected)||row.triage_result_sha256!==intakeDigest(context.triage.result)||!(row.status==='reserved'||succeeded)||succeeded!==Boolean(row.run_id)||succeeded!==Boolean(row.finished_at))throw new IntakeSnapshotRunAdmissionConflictError('Stored intake run admission failed immutable lineage verification');if(succeeded){const run=this.#ledger.get(row.run_id!,principal),job=run.jobs[0];if(run.jobs.length!==1||job?.repositoryId!==context.repository.id||intakeDigest(job.policySnapshot)!==row.repository_sha256||intakeDigest(job.workItemSnapshot)!==row.work_item_sha256||intakeDigest(job.triageDecision)!==intakeDigest(context.triage.result!.decision))throw new IntakeSnapshotRunAdmissionConflictError('Admitted run no longer matches immutable intake evidence');}return v.parse(IntakeSnapshotRunAdmissionSchema,{id:row.id,snapshotId:row.snapshot_id,triageId:row.triage_id,ownerId:row.owner_id,repositorySha256:row.repository_sha256,workItemSha256:row.work_item_sha256,triageResultSha256:row.triage_result_sha256,status:row.status,runId:row.run_id??undefined,reason:row.reason,runAdmissionAuthorized:row.status==='reserved',executionAuthorized:false,githubMutationAuthorized:false,createdAt:row.created_at,finishedAt:row.finished_at??undefined});}
	getForTriage(triageId:string,principal:Principal):IntakeSnapshotRunAdmission|undefined {this.#triages.get(triageId,principal);const row=this.#db.prepare('SELECT id FROM intake_snapshot_run_admissions WHERE triage_id=?').get(triageId) as {id:string}|undefined;return row?this.get(row.id,principal):undefined;}
	contextFor(id:string,principal:Principal):{admission:IntakeSnapshotRunAdmission;repository:RepositoryContract;workItem:WorkItem;decision:v.InferOutput<typeof TriageDecisionSchema>}{const admission=this.get(id,principal),context=this.#context(admission.triageId,principal);return{admission,repository:context.repository,workItem:deriveWorkItem(context.conversation.seed,context.snapshot.brief),decision:v.parse(TriageDecisionSchema,context.triage.result?.decision)};}
	settle(id:string,runId:string,principal:Principal):IntakeSnapshotRunAdmission {this.#db.transaction(()=>{const current=this.get(id,principal);if(current.status==='succeeded'){if(current.runId!==runId)throw new IntakeSnapshotRunAdmissionConflictError('Terminal intake run admission is immutable');return;}const changed=this.#db.prepare("UPDATE intake_snapshot_run_admissions SET status='succeeded',run_id=?,finished_at=? WHERE id=? AND status='reserved' AND run_id IS NULL").run(runId,this.#now().toISOString(),id);if(changed.changes!==1)throw new IntakeSnapshotRunAdmissionConflictError('Intake run admission settlement raced with another process');}).immediate();return this.get(id,principal);}
	#context(triageId:string,principal:Principal){const context=this.#triages.contextFor(triageId,principal);if(context.triage.status!=='succeeded'||!context.triage.result)throw new IntakeSnapshotRunAdmissionConflictError('Only successful independent snapshot triage can admit a run');const conversation=this.#conversations.get(context.snapshot.conversationId,principal);return{...context,conversation};}
	#findReplay(ownerId:string,key:string):AdmissionRow|undefined{return this.#db.prepare('SELECT * FROM intake_snapshot_run_admissions WHERE owner_id=? AND idempotency_key=?').get(ownerId,key) as AdmissionRow|undefined;}
}

export class IntakeSnapshotRunAdmissionService {
	readonly #store:IntakeSnapshotRunAdmissionStore;readonly #ledger:JobLedger;
	constructor(store=new IntakeSnapshotRunAdmissionStore(),ledger=new JobLedger()){this.#store=store;this.#ledger=ledger;}
	admit(id:string,principal:Principal):{admission:IntakeSnapshotRunAdmission;run:RunRecord}{const context=this.#store.contextFor(id,principal);const run=this.#ledger.admitWithExpectedPolicy({repositoryId:context.repository.id,workItem:context.workItem,triageDecision:context.decision},context.repository,principal,`intake-snapshot:${id}`);return{admission:this.#store.settle(id,run.id,principal),run};}
}
