import { randomUUID } from 'node:crypto';
import { chmodSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import Database from 'better-sqlite3';
import * as v from 'valibot';
import { dataPath } from '../paths.ts';
import { RepositoryIdSchema } from './contracts.ts';
import { IntakeBriefSchema, type IntakeBrief, type IntakeConversation } from './intake-conversation-contracts.ts';
import { IntakeConversationStore, intakeDigest } from './intake-conversation-store.ts';
import { ensureIntakeConversationSchema } from './intake-conversation-schema.ts';
import type { Principal } from './ledger.ts';

const Sha256Schema=v.pipe(v.string(),v.regex(/^[a-f0-9]{64}$/));
const FinalizeSchema=v.object({conversationId:v.pipe(v.string(),v.uuid()),expectedVersion:v.pipe(v.number(),v.integer(),v.minValue(1)),reason:v.pipe(v.string(),v.minLength(10),v.maxLength(2_000))});
const SourceTurnSchema=v.object({id:v.pipe(v.string(),v.uuid()),sequence:v.pipe(v.number(),v.integer(),v.minValue(1),v.maxValue(100)),role:v.picklist(['operator','assistant']),turnSha256:Sha256Schema});
export const IntakeBriefSnapshotSchema=v.object({id:v.pipe(v.string(),v.uuid()),conversationId:v.pipe(v.string(),v.uuid()),ownerId:v.pipe(v.string(),v.minLength(1),v.maxLength(500)),repositoryId:RepositoryIdSchema,sourceVersion:v.pipe(v.number(),v.integer(),v.minValue(1)),sourceTurnCount:v.pipe(v.number(),v.integer(),v.minValue(0),v.maxValue(100)),sourceTurnsSha256:Sha256Schema,sourceTurns:v.pipe(v.array(SourceTurnSchema),v.maxLength(100)),briefSha256:Sha256Schema,brief:IntakeBriefSchema,reason:v.pipe(v.string(),v.minLength(10),v.maxLength(2_000)),modelCallAuthorized:v.literal(false),triageAuthorized:v.literal(false),runAdmissionAuthorized:v.literal(false),githubMutationAuthorized:v.literal(false),createdAt:v.string()});
export type IntakeBriefSnapshot=v.InferOutput<typeof IntakeBriefSnapshotSchema>;
export class IntakeBriefSnapshotConflictError extends Error{}
export class IntakeBriefSnapshotForbiddenError extends Error{}
export class IntakeBriefSnapshotNotFoundError extends Error{}

interface SnapshotRow{id:string;conversation_id:string;owner_id:string;idempotency_key:string;request_sha256:string;source_version:number;source_turn_count:number;source_turns_sha256:string;source_turns_json:string;brief_sha256:string;brief_json:string;reason:string;created_at:string}
interface ConversationStateRow{id:string;owner_id:string;status:string;version:number;current_brief_sha256:string}

function sourceTurns(conversation:IntakeConversation):v.InferOutput<typeof SourceTurnSchema>[] {
	return conversation.turns.map((turn)=>v.parse(SourceTurnSchema,{id:turn.id,sequence:turn.sequence,role:turn.role,turnSha256:intakeDigest(turn)}));
}

export class IntakeBriefSnapshotStore {
	readonly #db:Database.Database;readonly #now:()=>Date;readonly #conversations:IntakeConversationStore;readonly #ownsConversations:boolean;
	constructor(path=dataPath('bobsled.db'),now:()=>Date=()=>new Date(),conversations?:IntakeConversationStore){if(path!==':memory:')mkdirSync(dirname(path),{recursive:true,mode:0o700});this.#db=new Database(path);if(path!==':memory:')chmodSync(path,0o600);this.#db.pragma('foreign_keys = ON');this.#db.pragma('journal_mode = WAL');this.#db.pragma('busy_timeout = 5000');this.#db.exec('CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)');ensureIntakeConversationSchema(this.#db);this.#conversations=conversations??new IntakeConversationStore(path,now);this.#ownsConversations=!conversations;this.#now=now;}
	close():void{if(this.#ownsConversations)this.#conversations.close();this.#db.close();}
	finalize(input:unknown,principal:Principal,idempotencyKey:string):IntakeBriefSnapshot {
		const request=v.parse(FinalizeSchema,input);if(!idempotencyKey||idempotencyKey.length>200)throw new IntakeBriefSnapshotConflictError('A bounded Idempotency-Key is required');const requestSha=intakeDigest(request);const replay=this.#findReplay(principal.id,idempotencyKey);if(replay){if(replay.request_sha256!==requestSha)throw new IntakeBriefSnapshotConflictError('Idempotency key was already used for different finalization input');return this.get(replay.id,principal);}
		const conversation=this.#conversations.get(request.conversationId,principal);if(conversation.status!=='active'||conversation.version!==request.expectedVersion)throw new IntakeBriefSnapshotConflictError('Conversation is terminal or changed; reload before finalizing');const provenance=sourceTurns(conversation),provenanceSha=intakeDigest(provenance),briefSha=intakeDigest(conversation.currentBrief);
		const id=this.#db.transaction(()=>{const concurrent=this.#findReplay(principal.id,idempotencyKey);if(concurrent){if(concurrent.request_sha256!==requestSha)throw new IntakeBriefSnapshotConflictError('Idempotency key was already used for different finalization input');return concurrent.id;}const row=this.#db.prepare('SELECT id,owner_id,status,version,current_brief_sha256 FROM intake_conversations WHERE id=?').get(conversation.id) as ConversationStateRow|undefined;if(!row)throw new IntakeBriefSnapshotNotFoundError('Conversation was not found');if(row.owner_id!==principal.id)throw new IntakeBriefSnapshotForbiddenError('Conversation belongs to another principal');if(row.status!=='active'||row.version!==conversation.version||row.current_brief_sha256!==briefSha)throw new IntakeBriefSnapshotConflictError('Conversation changed before finalization');const active=this.#db.prepare("SELECT id FROM intake_conversation_revisions WHERE conversation_id=? AND status IN ('reserved','running') LIMIT 1").get(conversation.id);if(active)throw new IntakeBriefSnapshotConflictError('Conversation has an active model revision');if(this.#db.prepare('SELECT id FROM intake_brief_snapshots WHERE conversation_id=?').get(conversation.id))throw new IntakeBriefSnapshotConflictError('Conversation already has an immutable final snapshot');const timestamp=this.#now().toISOString(),snapshotId=randomUUID();this.#db.prepare('INSERT INTO intake_brief_snapshots (id,conversation_id,owner_id,idempotency_key,request_sha256,source_version,source_turn_count,source_turns_sha256,source_turns_json,brief_sha256,brief_json,reason,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(snapshotId,conversation.id,principal.id,idempotencyKey,requestSha,conversation.version,provenance.length,provenanceSha,JSON.stringify(provenance),briefSha,JSON.stringify(conversation.currentBrief),request.reason,timestamp);const changed=this.#db.prepare("UPDATE intake_conversations SET status='finalized',version=version+1,updated_at=? WHERE id=? AND version=? AND status='active'").run(timestamp,conversation.id,conversation.version);if(changed.changes!==1)throw new IntakeBriefSnapshotConflictError('Conversation finalization raced with another process');return snapshotId;}).immediate();return this.get(id,principal);
	}
	getForConversation(conversationId:string,principal:Principal):IntakeBriefSnapshot {this.#conversations.get(conversationId,principal);const row=this.#db.prepare('SELECT id FROM intake_brief_snapshots WHERE conversation_id=?').get(conversationId) as {id:string}|undefined;if(!row)throw new IntakeBriefSnapshotNotFoundError('Final brief snapshot was not found');return this.get(row.id,principal);}
	get(id:string,principal:Principal):IntakeBriefSnapshot {
		const row=this.#db.prepare('SELECT * FROM intake_brief_snapshots WHERE id=?').get(id) as SnapshotRow|undefined;if(!row)throw new IntakeBriefSnapshotNotFoundError('Final brief snapshot was not found');if(row.owner_id!==principal.id)throw new IntakeBriefSnapshotForbiddenError('Final brief snapshot belongs to another principal');let brief:IntakeBrief,provenance:v.InferOutput<typeof SourceTurnSchema>[];try{brief=v.parse(IntakeBriefSchema,JSON.parse(row.brief_json));provenance=v.parse(v.array(SourceTurnSchema),JSON.parse(row.source_turns_json));}catch{throw new IntakeBriefSnapshotConflictError('Stored final brief snapshot is malformed');}const conversation=this.#conversations.get(row.conversation_id,principal),expectedProvenance=sourceTurns(conversation);if(conversation.status!=='finalized'||conversation.version!==row.source_version+1||conversation.repositoryId!==brief.repositoryId||row.source_turn_count!==provenance.length||intakeDigest(provenance)!==row.source_turns_sha256||intakeDigest(expectedProvenance)!==row.source_turns_sha256||intakeDigest(brief)!==row.brief_sha256||intakeDigest(conversation.currentBrief)!==row.brief_sha256||row.request_sha256!==intakeDigest({conversationId:row.conversation_id,expectedVersion:row.source_version,reason:row.reason}))throw new IntakeBriefSnapshotConflictError('Stored final brief snapshot failed immutable lineage verification');return v.parse(IntakeBriefSnapshotSchema,{id:row.id,conversationId:row.conversation_id,ownerId:row.owner_id,repositoryId:conversation.repositoryId,sourceVersion:row.source_version,sourceTurnCount:row.source_turn_count,sourceTurnsSha256:row.source_turns_sha256,sourceTurns:provenance,briefSha256:row.brief_sha256,brief,reason:row.reason,modelCallAuthorized:false,triageAuthorized:false,runAdmissionAuthorized:false,githubMutationAuthorized:false,createdAt:row.created_at});
	}
	#findReplay(owner:string,key:string):SnapshotRow|undefined{return this.#db.prepare('SELECT * FROM intake_brief_snapshots WHERE owner_id=? AND idempotency_key=?').get(owner,key) as SnapshotRow|undefined;}
}
