import { createHash, randomUUID } from 'node:crypto';
import { chmodSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import Database from 'better-sqlite3';
import * as v from 'valibot';
import { dataPath } from '../paths.ts';
import { RepositoryIdSchema, WorkItemSchema, type RepositoryContract } from './contracts.ts';
import { IntakeBriefSchema, IntakeConversationSchema, IntakeConversationTurnSchema, type IntakeBrief, type IntakeConversation } from './intake-conversation-contracts.ts';
import { ensureIntakeConversationSchema } from './intake-conversation-schema.ts';
import type { Principal } from './ledger.ts';
import { getRepository } from './repositories.ts';

const CreateSchema=v.object({repositoryId:RepositoryIdSchema,seed:WorkItemSchema,brief:IntakeBriefSchema});
const AppendSchema=v.object({expectedVersion:v.pipe(v.number(),v.integer(),v.minValue(1)),role:v.picklist(['operator','assistant']),text:v.pipe(v.string(),v.minLength(1),v.maxLength(20_000)),brief:IntakeBriefSchema});
const CancelSchema=v.object({expectedVersion:v.pipe(v.number(),v.integer(),v.minValue(1)),reason:v.pipe(v.string(),v.minLength(10),v.maxLength(2_000))});
export { IntakeBriefSchema, IntakeConversationSchema, IntakeConversationTurnSchema } from './intake-conversation-contracts.ts';
export type { IntakeBrief, IntakeConversation } from './intake-conversation-contracts.ts';
export class IntakeConversationConflictError extends Error{} export class IntakeConversationForbiddenError extends Error{} export class IntakeConversationNotFoundError extends Error{}
interface ConversationRow{id:string;owner_id:string;repository_id:string;idempotency_key:string;request_sha256:string;status:string;version:number;seed_json:string;current_brief_sha256:string;current_brief_json:string;terminal_reason:string|null;created_at:string;updated_at:string}
interface TurnRow{id:string;conversation_id:string;request_sha256:string;sequence:number;role:string;text:string;brief_sha256:string;brief_json:string;created_at:string}
function canonical(value:unknown):unknown{if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,canonical(item)]));return value;}
export function intakeDigest(value:unknown):string{return createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex');}
const digest=intakeDigest;

export class IntakeConversationStore{
	readonly #db:Database.Database;readonly #now:()=>Date;readonly #repository:(id:string)=>RepositoryContract|undefined;
	constructor(path=dataPath('bobsled.db'),now:()=>Date=()=>new Date(),repository=(id:string)=>getRepository(id)){if(path!==':memory:')mkdirSync(dirname(path),{recursive:true,mode:0o700});this.#db=new Database(path);if(path!==':memory:')chmodSync(path,0o600);this.#db.pragma('foreign_keys = ON');this.#db.pragma('journal_mode = WAL');this.#db.pragma('busy_timeout = 5000');this.#db.exec('CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)');ensureIntakeConversationSchema(this.#db);this.#now=now;this.#repository=repository;}
	close():void{this.#db.close();}
	list(principal:Principal):IntakeConversation[]{const rows=this.#db.prepare('SELECT id FROM intake_conversations WHERE owner_id=? ORDER BY updated_at DESC,id DESC').all(principal.id) as Array<{id:string}>;return rows.map(({id})=>this.get(id,principal));}
	create(input:unknown,principal:Principal,idempotencyKey:string):IntakeConversation{const request=v.parse(CreateSchema,input);if(!idempotencyKey||idempotencyKey.length>200)throw new IntakeConversationConflictError('A bounded Idempotency-Key is required');if(request.brief.repositoryId!==request.repositoryId)throw new IntakeConversationConflictError('Brief repository must match the explicitly selected repository');const repository=this.#repository(request.repositoryId);if(!repository?.enabled||!repository.capabilities.read)throw new IntakeConversationConflictError('Conversation repository is not enrolled for read-only intake');const sha=digest(request);const replay=this.#findReplay(principal.id,idempotencyKey);if(replay){if(replay.request_sha256!==sha)throw new IntakeConversationConflictError('Idempotency key was already used for different input');return this.get(replay.id,principal);}return this.#db.transaction(()=>{const concurrent=this.#findReplay(principal.id,idempotencyKey);if(concurrent){if(concurrent.request_sha256!==sha)throw new IntakeConversationConflictError('Idempotency key was already used for different input');return this.get(concurrent.id,principal);}const id=randomUUID(),timestamp=this.#now().toISOString();this.#db.prepare(`INSERT INTO intake_conversations (id,owner_id,repository_id,idempotency_key,request_sha256,status,version,seed_json,current_brief_sha256,current_brief_json,created_at,updated_at) VALUES (?,?,?,?,?,'active',1,?,?,?,?,?)`).run(id,principal.id,request.repositoryId,idempotencyKey,sha,JSON.stringify(request.seed),digest(request.brief),JSON.stringify(request.brief),timestamp,timestamp);return this.get(id,principal);}).immediate();}
	append(id:string,input:unknown,principal:Principal,idempotencyKey:string):IntakeConversation{const request=v.parse(AppendSchema,input);if(!idempotencyKey||idempotencyKey.length>200)throw new IntakeConversationConflictError('A bounded Idempotency-Key is required');const sha=digest(request);return this.#db.transaction(()=>{const row=this.#owned(id,principal);const replay=this.#db.prepare('SELECT * FROM intake_conversation_turns WHERE conversation_id=? AND idempotency_key=?').get(id,idempotencyKey) as TurnRow|undefined;if(replay){if(replay.request_sha256!==sha)throw new IntakeConversationConflictError('Turn idempotency key was already used for different input');return this.get(id,principal);}if(row.status!=='active')throw new IntakeConversationConflictError('Terminal conversation cannot accept another turn');this.#assertNoActiveRevision(id);if(row.version!==request.expectedVersion)throw new IntakeConversationConflictError('Conversation changed; reload before appending');if(request.brief.repositoryId!==row.repository_id)throw new IntakeConversationConflictError('A conversation cannot change its selected repository');const count=(this.#db.prepare('SELECT COUNT(*) AS count FROM intake_conversation_turns WHERE conversation_id=?').get(id) as {count:number}).count;if(count>=100)throw new IntakeConversationConflictError('Conversation reached its 100-turn limit');const timestamp=this.#now().toISOString();this.#db.prepare('INSERT INTO intake_conversation_turns (id,conversation_id,owner_id,idempotency_key,request_sha256,sequence,role,text,brief_sha256,brief_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),id,principal.id,idempotencyKey,sha,count+1,request.role,request.text,digest(request.brief),JSON.stringify(request.brief),timestamp);const changed=this.#db.prepare("UPDATE intake_conversations SET version=version+1,current_brief_sha256=?,current_brief_json=?,updated_at=? WHERE id=? AND version=? AND status='active'").run(digest(request.brief),JSON.stringify(request.brief),timestamp,id,request.expectedVersion);if(changed.changes!==1)throw new IntakeConversationConflictError('Conversation turn raced with another process');return this.get(id,principal);}).immediate();}
	cancel(id:string,input:unknown,principal:Principal):IntakeConversation{const request=v.parse(CancelSchema,input);return this.#db.transaction(()=>{const row=this.#owned(id,principal);if(row.status==='cancelled')return this.get(id,principal);this.#assertNoActiveRevision(id);if(row.version!==request.expectedVersion)throw new IntakeConversationConflictError('Conversation changed; reload before cancellation');const timestamp=this.#now().toISOString();const changed=this.#db.prepare("UPDATE intake_conversations SET status='cancelled',version=version+1,terminal_reason=?,updated_at=? WHERE id=? AND version=? AND status='active'").run(request.reason,timestamp,id,request.expectedVersion);if(changed.changes!==1)throw new IntakeConversationConflictError('Conversation cancellation raced with another process');return this.get(id,principal);}).immediate();}
	get(id:string,principal:Principal):IntakeConversation{const row=this.#owned(id,principal);let seed:v.InferOutput<typeof WorkItemSchema>,brief:IntakeBrief;try{seed=v.parse(WorkItemSchema,JSON.parse(row.seed_json));brief=v.parse(IntakeBriefSchema,JSON.parse(row.current_brief_json));}catch{throw new IntakeConversationConflictError('Stored conversation evidence is malformed');}if(brief.repositoryId!==row.repository_id||digest(brief)!==row.current_brief_sha256)throw new IntakeConversationConflictError('Stored conversation brief failed repository or digest verification');const rows=this.#db.prepare('SELECT * FROM intake_conversation_turns WHERE conversation_id=? ORDER BY sequence').all(id) as TurnRow[];const turns=rows.map((turn,index)=>{let turnBrief:IntakeBrief;try{turnBrief=v.parse(IntakeBriefSchema,JSON.parse(turn.brief_json));}catch{throw new IntakeConversationConflictError('Stored conversation turn is malformed');}if(turn.sequence!==index+1||turnBrief.repositoryId!==row.repository_id||digest(turnBrief)!==turn.brief_sha256)throw new IntakeConversationConflictError('Stored conversation turn failed sequence or digest verification');return v.parse(IntakeConversationTurnSchema,{id:turn.id,conversationId:id,sequence:turn.sequence,role:turn.role,text:turn.text,brief:turnBrief,createdAt:turn.created_at});});const finalized=row.status==='finalized',cancelled=row.status==='cancelled',snapshotCount=(this.#db.prepare('SELECT COUNT(*) AS count FROM intake_brief_snapshots WHERE conversation_id=?').get(id) as {count:number}).count;if(!['active','cancelled','finalized'].includes(row.status)||row.version!==turns.length+1+(cancelled||finalized?1:0)||rows.length>0&&digest(turns.at(-1)!.brief)!==row.current_brief_sha256||cancelled!==Boolean(row.terminal_reason)||snapshotCount!==(finalized?1:0))throw new IntakeConversationConflictError('Stored conversation lifecycle failed integrity verification');return v.parse(IntakeConversationSchema,{id:row.id,ownerId:row.owner_id,repositoryId:row.repository_id,status:row.status,version:row.version,seed,currentBrief:brief,turns,terminalReason:row.terminal_reason??undefined,intakeModelCallAuthorized:false,runAdmissionAuthorized:false,githubMutationAuthorized:false,createdAt:row.created_at,updatedAt:row.updated_at});}
	#owned(id:string,principal:Principal):ConversationRow{const row=this.#db.prepare('SELECT * FROM intake_conversations WHERE id=?').get(id) as ConversationRow|undefined;if(!row)throw new IntakeConversationNotFoundError('Intake conversation was not found');if(row.owner_id!==principal.id)throw new IntakeConversationForbiddenError('Intake conversation belongs to another principal');return row;}
	#assertNoActiveRevision(id:string):void{const active=this.#db.prepare("SELECT id FROM intake_conversation_revisions WHERE conversation_id=? AND status IN ('reserved','running') LIMIT 1").get(id);if(active)throw new IntakeConversationConflictError('Conversation has an active model revision');}
	#findReplay(owner:string,key:string):ConversationRow|undefined{return this.#db.prepare('SELECT * FROM intake_conversations WHERE owner_id=? AND idempotency_key=?').get(owner,key) as ConversationRow|undefined;}
}
