import { createHash, randomUUID } from 'node:crypto';
import { chmodSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import Database from 'better-sqlite3';
import * as v from 'valibot';
import { dataPath } from '../paths.ts';
import type { Principal } from './ledger.ts';
import { ensureMultiRepositoryChangeSetSchema } from './multi-repository-change-set-schema.ts';
import { MultiRepositoryPublicationRecoveryStore } from './multi-repository-publication-recovery-store.ts';
import { publicationRecoveryPlanDigest } from './multi-repository-publication-recovery-execution-store.ts';

const Sha256Schema=v.pipe(v.string(),v.regex(/^[a-f0-9]{64}$/));
const RequestSchema=v.variant('disposition',[
	v.object({recoveryPlanId:v.pipe(v.string(),v.uuid()),disposition:v.literal('human_rollback_required'),reason:v.pipe(v.string(),v.minLength(10),v.maxLength(2000))}),
	v.object({recoveryPlanId:v.pipe(v.string(),v.uuid()),disposition:v.literal('superseded_by_new_change_set'),supersedingChangeSetId:v.pipe(v.string(),v.uuid()),reason:v.pipe(v.string(),v.minLength(10),v.maxLength(2000))}),
]);
const ResultSchema=v.object({version:v.literal(1),recoveryPlanSha256:Sha256Schema,disposition:v.picklist(['human_rollback_required','superseded_by_new_change_set']),supersedingChangeSetId:v.optional(v.pipe(v.string(),v.uuid())),rollbackOrder:v.array(v.object({repositoryId:v.string(),publicationId:v.pipe(v.string(),v.uuid()),pullNumber:v.pipe(v.number(),v.integer(),v.minValue(1)),pullUrl:v.string(),action:v.literal('human_close_or_revert')})),retryExecutionAuthorized:v.literal(false),githubMutationAuthorized:v.literal(false),rollbackExecuted:v.literal(false),mergeAuthorized:v.literal(false)});
export const MultiRepositoryPublicationRecoveryDecisionSchema=v.object({id:v.pipe(v.string(),v.uuid()),recoveryPlanId:v.pipe(v.string(),v.uuid()),sourceExecutionId:v.pipe(v.string(),v.uuid()),changeSetId:v.pipe(v.string(),v.uuid()),ownerId:v.string(),disposition:v.picklist(['human_rollback_required','superseded_by_new_change_set']),supersedingChangeSetId:v.optional(v.pipe(v.string(),v.uuid())),reason:v.pipe(v.string(),v.minLength(10),v.maxLength(2000)),result:ResultSchema,createdAt:v.string()});
export type MultiRepositoryPublicationRecoveryDecision=v.InferOutput<typeof MultiRepositoryPublicationRecoveryDecisionSchema>;
export class MultiRepositoryPublicationRecoveryDecisionConflictError extends Error{}
export class MultiRepositoryPublicationRecoveryDecisionForbiddenError extends Error{}
export class MultiRepositoryPublicationRecoveryDecisionNotFoundError extends Error{}
interface Row{id:string;recovery_plan_id:string;source_execution_id:string;change_set_id:string;owner_id:string;idempotency_key:string;request_sha256:string;recovery_plan_sha256:string;disposition:string;superseding_change_set_id:string|null;result_sha256:string;result_json:string;reason:string;created_at:string}
function canonical(value:unknown):unknown{if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([k,item])=>[k,canonical(item)]));return value;}
function digest(value:unknown):string{return createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex');}

export class MultiRepositoryPublicationRecoveryDecisionStore{
	readonly #db:Database.Database;readonly #plans:MultiRepositoryPublicationRecoveryStore;readonly #ownsPlans:boolean;readonly #now:()=>Date;
	constructor(path=dataPath('bobsled.db'),now:()=>Date=()=>new Date(),plans?:MultiRepositoryPublicationRecoveryStore){if(path!==':memory:')mkdirSync(dirname(path),{recursive:true,mode:0o700});this.#db=new Database(path);if(path!==':memory:')chmodSync(path,0o600);this.#db.pragma('foreign_keys = ON');this.#db.pragma('journal_mode = WAL');this.#db.pragma('busy_timeout = 5000');this.#db.exec('CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)');ensureMultiRepositoryChangeSetSchema(this.#db);this.#plans=plans??new MultiRepositoryPublicationRecoveryStore(path,now);this.#ownsPlans=!plans;this.#now=now;}
	close():void{if(this.#ownsPlans)this.#plans.close();this.#db.close();}
	record(input:unknown,principal:Principal,idempotencyKey:string):MultiRepositoryPublicationRecoveryDecision{const request=v.parse(RequestSchema,input);if(!idempotencyKey||idempotencyKey.length>200)throw new MultiRepositoryPublicationRecoveryDecisionConflictError('A bounded Idempotency-Key is required');const requestSha=digest(request);const replay=this.#findReplay(principal.id,idempotencyKey);if(replay){if(replay.request_sha256!==requestSha)throw new MultiRepositoryPublicationRecoveryDecisionConflictError('Idempotency key was already used for different input');return this.get(replay.id,principal);}const plan=this.#plans.get(request.recoveryPlanId,principal);
		return this.#db.transaction(()=>{const concurrent=this.#findReplay(principal.id,idempotencyKey);if(concurrent){if(concurrent.request_sha256!==requestSha)throw new MultiRepositoryPublicationRecoveryDecisionConflictError('Idempotency key was already used for different input');return this.get(concurrent.id,principal);}if(this.#db.prepare('SELECT id FROM multi_repository_publication_recovery_executions WHERE recovery_plan_id=?').get(plan.id))throw new MultiRepositoryPublicationRecoveryDecisionConflictError('Recovery plan already has a retry execution');if(this.#db.prepare('SELECT id FROM multi_repository_publication_recovery_decisions WHERE recovery_plan_id=?').get(plan.id))throw new MultiRepositoryPublicationRecoveryDecisionConflictError('Recovery plan already has a terminal decision');if(request.disposition==='superseded_by_new_change_set')this.#assertSupersedingChangeSet(plan.changeSetId,request.supersedingChangeSetId,principal.id);const result=v.parse(ResultSchema,{version:1,recoveryPlanSha256:publicationRecoveryPlanDigest(plan),disposition:request.disposition,supersedingChangeSetId:request.disposition==='superseded_by_new_change_set'?request.supersedingChangeSetId:undefined,rollbackOrder:plan.result.rollbackOrder,retryExecutionAuthorized:false,githubMutationAuthorized:false,rollbackExecuted:false,mergeAuthorized:false});const id=randomUUID(),created=this.#now().toISOString();this.#db.prepare(`INSERT INTO multi_repository_publication_recovery_decisions (id,recovery_plan_id,source_execution_id,change_set_id,owner_id,idempotency_key,request_sha256,recovery_plan_sha256,disposition,superseding_change_set_id,result_sha256,result_json,reason,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,plan.id,plan.sourceExecutionId,plan.changeSetId,principal.id,idempotencyKey,requestSha,publicationRecoveryPlanDigest(plan),request.disposition,request.disposition==='superseded_by_new_change_set'?request.supersedingChangeSetId:null,digest(result),JSON.stringify(result),request.reason,created);return this.get(id,principal);}).immediate();}
	get(id:string,principal:Principal):MultiRepositoryPublicationRecoveryDecision{const row=this.#db.prepare('SELECT * FROM multi_repository_publication_recovery_decisions WHERE id=?').get(id) as Row|undefined;if(!row)throw new MultiRepositoryPublicationRecoveryDecisionNotFoundError('Recovery decision was not found');if(row.owner_id!==principal.id)throw new MultiRepositoryPublicationRecoveryDecisionForbiddenError('Recovery decision belongs to another principal');const plan=this.#plans.get(row.recovery_plan_id,principal);let result:v.InferOutput<typeof ResultSchema>;try{result=v.parse(ResultSchema,JSON.parse(row.result_json));}catch{throw new MultiRepositoryPublicationRecoveryDecisionConflictError('Stored recovery decision is malformed');}const expected=v.parse(ResultSchema,{version:1,recoveryPlanSha256:publicationRecoveryPlanDigest(plan),disposition:row.disposition,supersedingChangeSetId:row.superseding_change_set_id??undefined,rollbackOrder:plan.result.rollbackOrder,retryExecutionAuthorized:false,githubMutationAuthorized:false,rollbackExecuted:false,mergeAuthorized:false});if(row.recovery_plan_sha256!==publicationRecoveryPlanDigest(plan)||row.source_execution_id!==plan.sourceExecutionId||row.change_set_id!==plan.changeSetId||row.disposition!==result.disposition||row.superseding_change_set_id!==(result.supersedingChangeSetId??null)||digest(result)!==row.result_sha256||digest(result)!==digest(expected)||digest({recoveryPlanId:row.recovery_plan_id,disposition:row.disposition,...(row.superseding_change_set_id?{supersedingChangeSetId:row.superseding_change_set_id}:{}),reason:row.reason})!==row.request_sha256)throw new MultiRepositoryPublicationRecoveryDecisionConflictError('Stored recovery decision failed immutable parent or digest verification');if(result.disposition==='superseded_by_new_change_set')this.#assertSupersedingChangeSet(plan.changeSetId,result.supersedingChangeSetId!,principal.id);return v.parse(MultiRepositoryPublicationRecoveryDecisionSchema,{id:row.id,recoveryPlanId:row.recovery_plan_id,sourceExecutionId:row.source_execution_id,changeSetId:row.change_set_id,ownerId:row.owner_id,disposition:row.disposition,supersedingChangeSetId:row.superseding_change_set_id??undefined,reason:row.reason,result,createdAt:row.created_at});}
	#assertSupersedingChangeSet(sourceId:string,targetId:string,ownerId:string):void{if(sourceId===targetId)throw new MultiRepositoryPublicationRecoveryDecisionConflictError('Supersession requires a new change set');const target=this.#db.prepare('SELECT owner_id FROM multi_repository_change_sets WHERE id=?').get(targetId) as {owner_id:string}|undefined;if(!target||target.owner_id!==ownerId)throw new MultiRepositoryPublicationRecoveryDecisionConflictError('Superseding change set is unavailable to this principal');const sourceMembers=(this.#db.prepare('SELECT repository_id FROM multi_repository_change_set_members WHERE change_set_id=? ORDER BY repository_id').all(sourceId) as Array<{repository_id:string}>).map(({repository_id})=>repository_id);const targetMembers=(this.#db.prepare('SELECT repository_id FROM multi_repository_change_set_members WHERE change_set_id=? ORDER BY repository_id').all(targetId) as Array<{repository_id:string}>).map(({repository_id})=>repository_id);if(digest(sourceMembers)!==digest(targetMembers))throw new MultiRepositoryPublicationRecoveryDecisionConflictError('Superseding change set must cover the exact repository set');}
	#findReplay(owner:string,key:string):Row|undefined{return this.#db.prepare('SELECT * FROM multi_repository_publication_recovery_decisions WHERE owner_id=? AND idempotency_key=?').get(owner,key) as Row|undefined;}
}
