import { createHash, randomUUID } from 'node:crypto';
import { chmodSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import Database from 'better-sqlite3';
import * as v from 'valibot';
import { dataPath } from '../paths.ts';
import type { Principal } from './ledger.ts';
import { ensureMultiRepositoryChangeSetSchema } from './multi-repository-change-set-schema.ts';
import {
	MultiRepositoryPublicationRecoveryStore,
	type MultiRepositoryPublicationRecoveryPlan,
	type MultiRepositoryPublicationRecoveryPublication,
} from './multi-repository-publication-recovery-store.ts';

const Sha256Schema = v.pipe(v.string(), v.regex(/^[a-f0-9]{64}$/));
const PublicationStatusSchema = v.picklist(['blocked', 'pending', 'running', 'published', 'checks_pending', 'checks_failed', 'ready_for_human', 'merged', 'closed', 'failed']);
const SnapshotSchema = v.pipe(v.array(v.object({
	repositoryId: v.string(), publicationId: v.pipe(v.string(), v.uuid()), status: PublicationStatusSchema,
	attemptCount: v.pipe(v.number(), v.integer(), v.minValue(0)), pullNumber: v.optional(v.pipe(v.number(), v.integer(), v.minValue(1))), pullUrl: v.optional(v.string()),
})), v.minLength(2), v.maxLength(16));
const ResultSchema = v.object({
	recoveryPlanSha256: Sha256Schema, status: v.picklist(['succeeded', 'partial', 'blocked', 'failed']),
	members: SnapshotSchema, failedRepositoryId: v.optional(v.string()),
	reason: v.pipe(v.string(), v.minLength(1), v.maxLength(4_000)),
	githubMutationsAuthorized: v.literal(false), mergeAuthorized: v.literal(false), rollbackAuthorized: v.literal(false),
});
export const MultiRepositoryPublicationRecoveryExecutionSchema = v.object({
	id: v.pipe(v.string(), v.uuid()), recoveryPlanId: v.pipe(v.string(), v.uuid()), sourceExecutionId: v.pipe(v.string(), v.uuid()),
	changeSetId: v.pipe(v.string(), v.uuid()), ownerId: v.pipe(v.string(), v.minLength(1)),
	status: v.picklist(['reserved', 'prepared', 'running', 'succeeded', 'partial', 'blocked', 'failed']),
	publicationsStarted: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(16)), recoveryPlanSha256: Sha256Schema,
	reason: v.pipe(v.string(), v.minLength(10), v.maxLength(2_000)), createdAt: v.string(), startedAt: v.optional(v.string()), finishedAt: v.optional(v.string()),
	snapshot: v.optional(SnapshotSchema), result: v.optional(ResultSchema), retryExecutionAuthorized: v.boolean(),
	mergeAuthorized: v.literal(false), rollbackAuthorized: v.literal(false),
});
export type MultiRepositoryPublicationRecoveryExecution = v.InferOutput<typeof MultiRepositoryPublicationRecoveryExecutionSchema>;
export type MultiRepositoryPublicationRecoverySnapshot = v.InferOutput<typeof SnapshotSchema>;
export type MultiRepositoryPublicationRecoveryResult = v.InferOutput<typeof ResultSchema>;
export class MultiRepositoryPublicationRecoveryExecutionConflictError extends Error {}
export class MultiRepositoryPublicationRecoveryExecutionForbiddenError extends Error {}
export class MultiRepositoryPublicationRecoveryExecutionNotFoundError extends Error {}

const ReserveSchema = v.object({ recoveryPlanId: v.pipe(v.string(), v.uuid()), reason: v.pipe(v.string(), v.minLength(10), v.maxLength(2_000)) });
interface Row { id:string; recovery_plan_id:string; source_execution_id:string; change_set_id:string; owner_id:string; idempotency_key:string; request_sha256:string; recovery_plan_sha256:string; reason:string; status:string; publications_started:number; created_at:string; started_at:string|null; finished_at:string|null; result_sha256:string|null; result_json:string|null }
interface PreflightRow { snapshot_sha256:string; snapshot_json:string }
function canonical(value:unknown):unknown { if(Array.isArray(value)) return value.map(canonical); if(value&&typeof value==='object') return Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([k,item])=>[k,canonical(item)])); return value; }
function digest(value:unknown):string { return createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex'); }
export function publicationRecoveryPlanDigest(plan:MultiRepositoryPublicationRecoveryPlan):string { return digest({ id:plan.id, sourceExecutionId:plan.sourceExecutionId, authorizationId:plan.authorizationId, changeSetId:plan.changeSetId, ownerId:plan.ownerId, result:plan.result, createdAt:plan.createdAt }); }
function snapshotOf(publications:readonly MultiRepositoryPublicationRecoveryPublication[]):MultiRepositoryPublicationRecoverySnapshot { return v.parse(SnapshotSchema,publications.map((item)=>({repositoryId:item.repositoryId,publicationId:item.id,status:item.status,attemptCount:item.attemptCount,pullNumber:item.pullNumber,pullUrl:item.pullUrl}))); }

export class MultiRepositoryPublicationRecoveryExecutionStore {
	readonly #db:Database.Database; readonly #plans:MultiRepositoryPublicationRecoveryStore; readonly #ownsPlans:boolean; readonly #now:()=>Date;
	constructor(path=dataPath('bobsled.db'),now:()=>Date=()=>new Date(),plans?:MultiRepositoryPublicationRecoveryStore) {
		if(path!==':memory:') mkdirSync(dirname(path),{recursive:true,mode:0o700}); this.#db=new Database(path); if(path!==':memory:') chmodSync(path,0o600);
		this.#db.pragma('foreign_keys = ON'); this.#db.pragma('journal_mode = WAL'); this.#db.pragma('busy_timeout = 5000'); this.#db.exec('CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)'); ensureMultiRepositoryChangeSetSchema(this.#db);
		this.#plans=plans??new MultiRepositoryPublicationRecoveryStore(path,now); this.#ownsPlans=!plans; this.#now=now;
	}
	close():void { if(this.#ownsPlans)this.#plans.close(); this.#db.close(); }
	planFor(id:string,principal:Principal):MultiRepositoryPublicationRecoveryPlan { return this.#plans.get(this.get(id,principal).recoveryPlanId,principal); }
	reserve(input:unknown,principal:Principal,idempotencyKey:string):MultiRepositoryPublicationRecoveryExecution {
		const request=v.parse(ReserveSchema,input); if(!idempotencyKey||idempotencyKey.length>200) throw new MultiRepositoryPublicationRecoveryExecutionConflictError('A bounded Idempotency-Key is required'); const requestSha=digest(request);
		const replay=this.#findReplay(principal.id,idempotencyKey); if(replay){if(replay.request_sha256!==requestSha)throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Idempotency key was already used for different input');return this.get(replay.id,principal);}
		const plan=this.#plans.get(request.recoveryPlanId,principal); if(plan.result.status!=='retryable'||plan.result.retryOrder.length===0)throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Recovery plan does not authorize a bounded retry');
		return this.#db.transaction(()=>{const concurrent=this.#findReplay(principal.id,idempotencyKey);if(concurrent){if(concurrent.request_sha256!==requestSha)throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Idempotency key was already used for different input');return this.get(concurrent.id,principal);}if(this.#db.prepare('SELECT id FROM multi_repository_publication_recovery_decisions WHERE recovery_plan_id=?').get(plan.id))throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Recovery plan already has an operator decision');if(this.#db.prepare('SELECT id FROM multi_repository_publication_recovery_executions WHERE recovery_plan_id=?').get(plan.id))throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Recovery plan already has a retry execution');const id=randomUUID(),created=this.#now().toISOString();this.#db.prepare(`INSERT INTO multi_repository_publication_recovery_executions (id,recovery_plan_id,source_execution_id,change_set_id,owner_id,idempotency_key,request_sha256,recovery_plan_sha256,reason,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,'reserved',?)`).run(id,plan.id,plan.sourceExecutionId,plan.changeSetId,principal.id,idempotencyKey,requestSha,publicationRecoveryPlanDigest(plan),request.reason,created);return this.get(id,principal);}).immediate();
	}
	get(id:string,principal:Principal):MultiRepositoryPublicationRecoveryExecution {
		const row=this.#db.prepare('SELECT * FROM multi_repository_publication_recovery_executions WHERE id=?').get(id) as Row|undefined;if(!row)throw new MultiRepositoryPublicationRecoveryExecutionNotFoundError('Recovery execution was not found');if(row.owner_id!==principal.id)throw new MultiRepositoryPublicationRecoveryExecutionForbiddenError('Recovery execution belongs to another principal');const plan=this.#plans.get(row.recovery_plan_id,principal);const preflight=this.#db.prepare('SELECT * FROM multi_repository_publication_recovery_preflights WHERE execution_id=?').get(id) as PreflightRow|undefined;
		let snapshot:MultiRepositoryPublicationRecoverySnapshot|undefined;if(preflight){try{snapshot=v.parse(SnapshotSchema,JSON.parse(preflight.snapshot_json));}catch{throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Stored recovery preflight is malformed');}if(digest(snapshot)!==preflight.snapshot_sha256||digest(snapshot)!==digest(plan.result.members.map((member)=>({repositoryId:member.repositoryId,publicationId:member.publicationId,status:member.currentStatus,attemptCount:member.attemptCount,pullNumber:member.pullNumber,pullUrl:member.pullUrl}))))throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Stored recovery preflight drifted from its immutable plan');}
		let result:MultiRepositoryPublicationRecoveryResult|undefined;if(row.result_json){try{result=v.parse(ResultSchema,JSON.parse(row.result_json));}catch{throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Stored recovery result is malformed');}const plannedByRepository=new Map(plan.result.members.map((member)=>[member.repositoryId,member]));if(!row.result_sha256||digest(result)!==row.result_sha256||result.recoveryPlanSha256!==row.recovery_plan_sha256||result.members.length!==plan.result.members.length||result.members.some((member,index)=>{const planned=plan.result.members[index];return !planned||member.repositoryId!==planned.repositoryId||member.publicationId!==planned.publicationId;})||result.failedRepositoryId&&!plannedByRepository.has(result.failedRepositoryId))throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Stored recovery result failed plan or digest verification');}
		const terminal=['succeeded','partial','blocked','failed'].includes(row.status);const unattempted=new Set(plan.result.retryOrder.slice(row.publications_started));if(row.recovery_plan_sha256!==publicationRecoveryPlanDigest(plan)||row.source_execution_id!==plan.sourceExecutionId||row.change_set_id!==plan.changeSetId||digest({recoveryPlanId:plan.id,reason:row.reason})!==row.request_sha256||(row.status==='reserved'&&Boolean(snapshot))||(['prepared','running'].includes(row.status)&&!snapshot)||terminal!==Boolean(result)||(result&&result.status!==row.status)||(terminal!==Boolean(row.finished_at))||row.publications_started>plan.result.retryOrder.length||(row.status==='succeeded'&&row.publications_started!==plan.result.retryOrder.length)||(row.status==='partial'&&(row.publications_started<1||!result?.failedRepositoryId))||Boolean(result?.members.some((member)=>{const planned=plan.result.members.find((candidate)=>candidate.repositoryId===member.repositoryId)!;return (!plan.result.retryOrder.includes(member.repositoryId)||unattempted.has(member.repositoryId))&&member.status!==planned.currentStatus;})))throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Stored recovery execution failed lifecycle or parent verification');
		return v.parse(MultiRepositoryPublicationRecoveryExecutionSchema,{id:row.id,recoveryPlanId:row.recovery_plan_id,sourceExecutionId:row.source_execution_id,changeSetId:row.change_set_id,ownerId:row.owner_id,status:row.status,publicationsStarted:row.publications_started,recoveryPlanSha256:row.recovery_plan_sha256,reason:row.reason,createdAt:row.created_at,startedAt:row.started_at??undefined,finishedAt:row.finished_at??undefined,snapshot,result,retryExecutionAuthorized:row.status==='prepared',mergeAuthorized:false,rollbackAuthorized:false});
	}
	recordPreflight(id:string,publications:readonly MultiRepositoryPublicationRecoveryPublication[],principal:Principal):MultiRepositoryPublicationRecoveryExecution { const snapshot=snapshotOf(publications);this.#db.transaction(()=>{const current=this.get(id,principal);if(current.status!=='reserved')throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Only a reserved recovery may record preflight');const plan=this.#plans.get(current.recoveryPlanId,principal);const expected=plan.result.members.map((member)=>({repositoryId:member.repositoryId,publicationId:member.publicationId,status:member.currentStatus,attemptCount:member.attemptCount,pullNumber:member.pullNumber,pullUrl:member.pullUrl}));if(digest(snapshot)!==digest(expected))throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Current publications no longer match the recovery plan');this.#db.prepare('INSERT INTO multi_repository_publication_recovery_preflights (execution_id,snapshot_sha256,snapshot_json,created_at) VALUES (?,?,?,?)').run(id,digest(snapshot),JSON.stringify(snapshot),this.#now().toISOString());const changed=this.#db.prepare("UPDATE multi_repository_publication_recovery_executions SET status='prepared' WHERE id=? AND status='reserved'").run(id);if(changed.changes!==1)throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Recovery preflight raced with another process');}).immediate();return this.get(id,principal); }
	claim(id:string,principal:Principal):{execution:MultiRepositoryPublicationRecoveryExecution;newlyClaimed:boolean}{let newlyClaimed=false;this.#db.transaction(()=>{const current=this.get(id,principal);if(current.status==='running'||['succeeded','partial','blocked','failed'].includes(current.status))return;if(current.status!=='prepared')throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Recovery execution lacks passing preflight');const changed=this.#db.prepare("UPDATE multi_repository_publication_recovery_executions SET status='running',started_at=? WHERE id=? AND status='prepared'").run(this.#now().toISOString(),id);if(changed.changes!==1)throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Recovery claim raced with another process');newlyClaimed=true;}).immediate();return{execution:this.get(id,principal),newlyClaimed};}
	recordPublicationStart(id:string,principal:Principal,index:number):MultiRepositoryPublicationRecoveryExecution{this.#db.transaction(()=>{const current=this.get(id,principal);const plan=this.#plans.get(current.recoveryPlanId,principal);if(current.status!=='running'||current.publicationsStarted!==index||index>=plan.result.retryOrder.length)throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Recovery start does not match the one-use retry order');const changed=this.#db.prepare('UPDATE multi_repository_publication_recovery_executions SET publications_started=publications_started+1 WHERE id=? AND status=\'running\' AND publications_started=?').run(id,index);if(changed.changes!==1)throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Recovery start raced with another process');}).immediate();return this.get(id,principal);}
	settle(id:string,input:unknown,principal:Principal):MultiRepositoryPublicationRecoveryExecution{const result=v.parse(ResultSchema,input);this.#db.transaction(()=>{const current=this.get(id,principal);if(['succeeded','partial','blocked','failed'].includes(current.status)){if(digest(current.result)!==digest(result))throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Terminal recovery evidence is immutable');return;}if(!['reserved','prepared','running'].includes(current.status)||result.recoveryPlanSha256!==current.recoveryPlanSha256)throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Recovery execution is not settleable');if(['reserved','prepared'].includes(current.status)&&(result.status!=='blocked'||current.publicationsStarted!==0))throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Only zero-side-effect preflight blockage may settle before claim');if(result.status==='succeeded'&&result.members.some(({status})=>!['published','checks_pending','checks_failed','ready_for_human'].includes(status)))throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Successful recovery requires every linked draft to exist');const changed=this.#db.prepare("UPDATE multi_repository_publication_recovery_executions SET status=?,result_sha256=?,result_json=?,finished_at=? WHERE id=? AND status IN ('reserved','prepared','running')").run(result.status,digest(result),JSON.stringify(result),this.#now().toISOString(),id);if(changed.changes!==1)throw new MultiRepositoryPublicationRecoveryExecutionConflictError('Recovery settlement raced with another process');}).immediate();return this.get(id,principal);}
	#findReplay(owner:string,key:string):Row|undefined{return this.#db.prepare('SELECT * FROM multi_repository_publication_recovery_executions WHERE owner_id=? AND idempotency_key=?').get(owner,key) as Row|undefined;}
}
